version: "2"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    devices:
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /home/[USER]/media/configs/cache:/cache
      - /home/[USER]/media/tv:/data/tv
      - /home/[USER]/media/movies:/data/movies
    environment:
      - jellyfin_publishedserverurl=10.0.0.37
      - PUID=1000
      - PGID=1000
    ports:
      - 80:8096
    restart: unless-stopped

  jackettvpn:
    image: dyonr/jackettvpn
    container_name: jackett
    hostname: jackett
    privileged: true
    volumes:
      - /home/[USER]/media/configs/jackett:/config
      - /home/[USER]/media/configs/wireguard:/config/wireguard
      - /home/[USER]/media/torrents:/blackhole
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=10.0.0.0/24
      - PUID=1000
      - PGID=1000
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrent
    hostname: qbittorrent
    privileged: true
    volumes:
      - /home/[USER]/media/configs/qbittorrent:/config
      - /home/[USER]/media/configs/wireguard:/config/wireguard
      - /home/[USER]/media/torrents/:/downloads
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=10.0.0.0/24
      - PUID=1000
      - PGID=1000
    ports:
      - 8765:8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    environment:
      - tz=europe/london
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/[USER]/media/configs/radarr:/config
      - /home/[USER]/media/movies:/movies
      - /home/[USER]/media/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - tz=europe/london
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/[USER]/media/configs/sonarr:/config
      - /home/[USER]/media/tv:/tv
      - /home/[USER]/media/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/[USER]/media/configs/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
