version: "2"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    user: 1000:1000
    devices:
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - /home/alex/media/configs/cache:/cache
      - /home/alex/media/tv:/data/tv
      - /home/alex/media/movies:/data/movies
    environment:
      - jellyfin_publishedserverurl=10.0.0.37
    ports:
      - 80:8096
    restart: unless-stopped

  jackettvpn:
    image: dyonr/jackettvpn
    container_name: jackett
    hostname: jackett
    privileged: true
    volumes:
      - /home/alex/media/configs/jackett:/config
      - /home/alex/media/configs/wireguard:/config/wireguard
      - /home/alex/media/torrents:/blackhole
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=10.0.0.0/24
    ports:
      - 9117:9117
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    hostname: organizr
    restart: unless-stopped
    ports:
      - 90:80
    volumes:
      - /home/alex/media/configs/organizr:/config
    environment:
      - fpm=true
      - branch=v2-master
      - puid=998
      - pgid=100
      - tz=europe/london

  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrent
    hostname: qbittorrent
    privileged: true
    volumes:
      - /home/alex/media/configs/qbittorrent:/config
      - /home/alex/media/configs/wireguard:/config/wireguard
      - /home/alex/media/torrents/:/downloads
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=10.0.0.0/24
    ports:
      - 8765:8080
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    hostname: radarr
    environment:
      - puid=998
      - pgid=100
      - tz=europe/london
      - umask_set=022
    volumes:
      - /home/alex/media/configs/radarr:/config
      - /home/alex/media/movies:/movies
      - /home/alex/media/torrents:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    hostname: sabnzbd
    environment:
      - puid=998
      - pgid=100
      - tz=europe/london
    volumes:
      - /home/alex/media/configs/sabnzbd:/config
      - /home/alex/media/downloads:/downloads
      - /home/alex/media/downloads/incomplete:/incomplete-downloads
    ports:
      - 8181:8080
      - 9191:9090
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    environment:
      - puid=998
      - pgid=100
      - tz=europe/london
      - umask_set=022
    volumes:
      - /home/alex/media/configs/sonarr:/config
      - /home/alex/media/tv:/tv
      - /home/alex/media/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
